[package]
name = "acs"
version = "0.8.0"
edition = "2021"
authors = ["Antonio Caggiano <info@antoniocaggiano.eu>"]
license = "MIT"

[[test]]
name = "vm"
path = "tests/vm/mod.rs"

[dependencies]
png = "0.17.6"
sdl2 = "0.35.2"
