name: ci

on:
  push:
    branches: [ main, ci ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
          pkg
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: Deps
      run: |
        sudo apt update
        sudo apt install libsdl2-dev -y

    - name: Check
      run: cargo check --release

    - name: Test
      run: |
        git submodule update --init
        cargo test --release

    - name: Wasm
      run: |
        curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
        wasm-pack build --target nodejs --release --scope fahien
        echo '//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}' > ~/.npmrc
        echo 'registry=https://npm.pkg.github.com/fahien' > pkg/.npmrc

    - name: Publish
      run: npm publish --access public
      working-directory: ./pkg
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Web
      run: |
        RUSTDOCFLAGS="--default-theme ayu" cargo doc --no-deps
        mv target/doc/acs target/doc/doc

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: target/doc
